name: my first workflow

on : push

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Verify Python Version
      run: python -version

    - name: Install dependencies
      run : python -m pip install --upgrade pip

  
            
  
